import numpy as np
arr=np.array([10,20,30])
print(arr)
print(np.max(arr))
print(np.min(arr))
print(np.mean((arr)))
print(np.sum(arr))
print(np.zeros(8))
print(np.ones((5)))
print("Even numbers list is:",np.arange(2,10,2))
print("odd numbers list is:",np.arange(1,10,2))

n=int(input("Enter the size of the array:"))
ele=list(map(int,input("Enter elements:").split()))
print("Array elements are:",np.array(ele))
